--- 
title: "Verkefni 5"
author: Árni Víðir Jóhannesson & Ottó Hólm Reynisson
date: 11.október 2016
subject: null
header-includes: 
   - \usepackage{longtable} 
   - \usepackage{graphics} 
   - \usepackage[icelandic]{babel} 
   - \usepackage{tabularx} 
   - \usepackage{booktabs,colortbl,xcolor} 
output: 
  pdf_document: 
    number_sections: no 
    toc: no 
    toc_depth: 2 
    fig_caption: yes 
  html_document: 
    self_contained: yes 
  word_document: 
    toc: yes 
    toc_depth: '2' 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE)
```


```{r echo=FALSE, message=FALSE, error=FALSE}
# Bara að gera setup ef það þarf
if(!exists("dt.RE_data")){ source("setUp.R")}
source("utilz.R")
source("outliers.R")
source("transformation.R")
source("testArni.R")
source("variableSelection.R")

lm.all <- lm(nuvirdi ~ .,data=train)

```


```{r child='diagnostics.rmd'}

```

\newpage

```{r child='transformation.rmd'}

```

\newpage

```{r child='variableSelection.rmd'}

```


\newpage

```{r child='setUp.rmd'}

```

```{r child='outliers.rmd'}

```

```{r child='radjusted.rmd'}

```

```{r child='variableSelectionR.rmd'}

```

