--- 
title: "Verkefni 5"
author: Ottó Hólm Reynisson
date: 15.september 2016
subject: null
header-includes: 
   - \usepackage{longtable} 
   - \usepackage{graphics} 
   - \usepackage[icelandic]{babel} 
   - \usepackage{tabularx} 
   - \usepackage{booktabs,colortbl,xcolor} 
output: 
  pdf_document: 
    number_sections: no 
    toc: no 
    toc_depth: 2 
    fig_caption: yes 
  html_document: 
    self_contained: yes 
  word_document: 
    toc: yes 
    toc_depth: '2' 
---

```{r}
# Bara að gera setup ef það þarf
if(!exists("dt.RE_data")){ source("setUp.R")}
source("utilz.R")
source("outliers.R")
source("testArni.R")

lm.all <- lm(nuvirdi ~ .,data=train)
#ggpairs(dt.RE_data)


```


```{r}
###################################### R squared adjusted fyrir lm.all
Radj.all <- CalculateRadjusted(lm.all, test) # 0.7436628
```

```{r}
#################################### lm.allNoOutliers Here I take out all outliers and get a new model #################
lm.allNoOutlier <- removeOutliersWStdResMoreThanThree(lm.all)
Radj.allNoOutliers <- CalculateRadjusted(lm.allNoOutlier, test) # 0.7328961
```

```{r}
#################################### lm.allNoInfluential Here I take out all influential points and get a new model ####
lm.allNoInfluential <- removeInfluential(lm.all,maxCookDistance = 4/n)
Radj.allNoInfluential <- CalculateRadjusted(lm.allNoInfluential, test) # 0.7327364
```

```{r}
#################################### prófa boxcox til að transforma response breytunni (nuvirdi) #######################
# Start by transforming the training and test datasets
bc <- boxcox(lm.all)
lambda.all <- with(bc, x[which.max(y)])

trainTransf <- train
testTransf <- test
trainTransf$nuvirdi <- yjPower(train$nuvirdi, lambda.all)
testTransf$nuvirdi <- yjPower(test$nuvirdi, lambda.all)

lm.allYTransformed <- lm(nuvirdi ~ ., data = trainTransf)

Radj.allYTransformed <- CalculateRadjusted(lm.allYTransformed, testTransf) # 0.7890585

lm.stepYtransformed <- step(lm.allYTransformed)

# Nota step á modelið þar sem búið var að transform-a nuvirdi
Radj.stepYtransformed <- CalculateRadjusted(lm.stepYtransformed, testTransf) # 0.7913491
```


```{r}
######################  Föll fyrir residuals og annað er í outliers.R skránni  ######

# funcions to plot residuals and leverage
indexPlotResiduals(lm.all)
indexPlotJackResiduals(lm.all)
indexPlotLeverage(lm.all)
indexPlotStResiduals(lm.all)
# blue dots have high residuals and green have high leverage
indexPlotCookdistance(lm.all)


```

```{r}
##################### Trying to use step forward and backwards #########################
# With outliers and influential points
slm.allBack <- step(lm.all)
slm.allForw <- step(lm.all,direction = "forward")
Radj.stepBackwards <- CalculateRadjusted(slm.allBack, test) # 0.7469181
Radj.stepForwards <- CalculateRadjusted(slm.allForw, test) # 0.7436628

# Without outliers
slm.allBackNoOutliers <- step(lm.allNoOutlier)
slm.allForwNoOutliers <- step(lm.allNoOutlier,direction = "forward")
Radj.stepBackNoOutliers <- CalculateRadjusted(slm.allBackNoOutliers, test) # 0.7335344
Radj.stepForwNoOutliers <- CalculateRadjusted(slm.allForwNoOutliers, test) # 0.7328961

# Without influential points
slm.allBackNoInfl <- step(lm.allNoInfluential)
slm.allForwNoInfl <- step(lm.allNoInfluential,direction = "forward")
Radj.stepBackNoInfl <- CalculateRadjusted(slm.allBackNoInfl, test) # 0.73425
Radj.stepForwNoInfl <- CalculateRadjusted(slm.allForwNoInfl, test) # 0.7327364
```


```{r}

lm.test <- lm(nuvirdi ~ byggar + haednr)

#Call:
#lm(formula = nuvirdi ~ teg_eign + byggar + haednr + lyfta + ibm2 + 
#    fjhaed + fjbilast + fjbkar + fjsturt + fjklos + fjeld + fjherb + 
#    fjstof + fjgeym + stig10 + ibteg, data = train)
#
#Residuals:
#   Min     1Q Median     3Q    Max 
#-30737  -4584   -399   3705 113946 

#Coefficients:
#                    Estimate Std. Error t value Pr(>|t|)    
#(Intercept)        293911.47   45342.10   6.482 1.23e-10 ***
#teg_eignIbudareign -11194.68    1090.53 -10.265  < 2e-16 ***
#teg_eignParhus      -5620.75    1698.00  -3.310 0.000955 ***
#teg_eignRadhus      -9691.17    1147.17  -8.448  < 2e-16 ***
#byggar               -156.46      12.62 -12.400  < 2e-16 ***
#haednr                314.71     187.87   1.675 0.094111 .  
#lyfta                3809.14     540.88   7.042 2.89e-12 ***
#ibm2                  217.23      11.78  18.442  < 2e-16 ***
#fjhaed              -4190.36     678.61  -6.175 8.55e-10 ***
#fjbilast             -734.70     748.03  -0.982 0.326175    
#fjbkar               1523.20     695.37   2.190 0.028645 *  
#fjsturt               513.50     562.29   0.913 0.361272    
#fjklos               1182.28     766.01   1.543 0.122943    
#fjeld               -1352.79    1381.92  -0.979 0.327780    
#fjherb                 21.90     287.69   0.076 0.939323    
#fjstof               1420.22     430.52   3.299 0.000994 ***
#fjgeym                -22.28     357.62  -0.062 0.950331    
#stig10               3238.86    3758.53   0.862 0.388974    
#ibtegSérbýli        -4911.56    4971.94  -0.988 0.323386    
#---
#Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

#Residual standard error: 8568 on 1467 degrees of freedom
#Multiple R-squared:  0.7088,	Adjusted R-squared:  0.7052 
#F-statistic: 198.3 on 18 and 1467 DF,  p-value: < 2.2e-16

### Getum við því hent út 
#fjbilast, 
#fjsturt, 
#fjeld, 
#fjherb, 
#fjgeym ,
#stig10, 
#ibtegSerbyli?

lm.nytt<- lm(nuvirdi ~ teg_eign + byggar + haednr + lyfta + ibm2 + fjhaed  + fjbkar + fjklos + fjstof, data = train)

summary(lm.nytt)


diag.all <- fortify(lm.all)

lm.prufa <- lm(nuvirdi ~ teg_eign + byggar + lyfta + ibm2 + fjhaed + fjbkar + fjsturt + fjklos + fjeld + fjherb + fjstof + fjgeym + ibteg, data = train)

summary(lm.prufa)

diag.prufa <- fortify(lm.prufa)
```

```{r}
################################################# PLOTS
indexPlotResiduals(lm.all)
QQplotResiduals(lm.all)
QQplotResiduals(lm.allYTransformed)
QQplotResiduals(lm.stepYtransformed)
```


